const DEFAULT_CHART_OF_ACCOUNTS = [
  { code: "1000", name: "Cash & Cash Equivalents", category: "Assets" },
  { code: "1010", name: "Savings Account", category: "Assets" },
  { code: "1100", name: "Accounts Receivable", category: "Assets" },
  { code: "1200", name: "Inventory", category: "Assets" },
  { code: "1300", name: "Prepaid Expenses", category: "Assets" },
  { code: "1400", name: "Other Current Assets", category: "Assets" },
  { code: "1500", name: "Property, Plant & Equipment", category: "Assets" },
  { code: "1510", name: "Accumulated Depreciation", category: "Assets" },
  { code: "1600", name: "Intangible Assets", category: "Assets" },
  { code: "1700", name: "Security Deposits", category: "Assets" },
  { code: "1800", name: "Right-of-Use Asset (ASC 842)", category: "Assets" },
  { code: "1810", name: "Accumulated Amortization - ROU", category: "Assets" },
  { code: "2000", name: "Accounts Payable", category: "Liabilities" },
  { code: "2100", name: "Accrued Liabilities", category: "Liabilities" },
  { code: "2200", name: "Short-Term Debt", category: "Liabilities" },
  { code: "2300", name: "Deferred Revenue", category: "Liabilities" },
  { code: "2400", name: "Lease Liability - Current (ASC 842)", category: "Liabilities" },
  { code: "2450", name: "Lease Liability - Non-Current (ASC 842)", category: "Liabilities" },
  { code: "2500", name: "Long-Term Debt", category: "Liabilities" },
  { code: "2600", name: "Notes Payable", category: "Liabilities" },
  { code: "3000", name: "Common Stock", category: "Equity" },
  { code: "3100", name: "Retained Earnings", category: "Equity" },
  { code: "3200", name: "Additional Paid-In Capital", category: "Equity" },
  { code: "4000", name: "Sales Revenue", category: "Revenue" },
  { code: "4100", name: "Service Revenue", category: "Revenue" },
  { code: "4200", name: "Other Income", category: "Revenue" },
  { code: "4300", name: "Interest Income", category: "Revenue" },
  { code: "5000", name: "Cost of Goods Sold", category: "Expenses" },
  { code: "5100", name: "Salaries & Wages", category: "Expenses" },
  { code: "5200", name: "Rent & Occupancy", category: "Expenses" },
  { code: "5300", name: "Utilities", category: "Expenses" },
  { code: "5400", name: "Marketing & Advertising", category: "Expenses" },
  { code: "5500", name: "Travel & Entertainment", category: "Expenses" },
  { code: "5600", name: "Office Supplies", category: "Expenses" },
  { code: "5700", name: "Insurance", category: "Expenses" },
  { code: "5800", name: "Professional Services", category: "Expenses" },
  { code: "5900", name: "Technology & Software", category: "Expenses" },
  { code: "6000", name: "Depreciation & Amortization", category: "Expenses" },
  { code: "6050", name: "ROU Asset Amortization", category: "Expenses" },
  { code: "6100", name: "Interest Expense", category: "Expenses" },
  { code: "6150", name: "Lease Expense - Operating", category: "Expenses" },
  { code: "6200", name: "Miscellaneous Expense", category: "Expenses" },
  { code: "6300", name: "Bad Debt Expense", category: "Expenses" },
  { code: "6400", name: "Payroll Tax Expense", category: "Expenses" },
  { code: "6500", name: "Employee Benefits", category: "Expenses" },
];

const PROJECTS = ["General", "Marketing Campaign", "Office Renovation", "Product Launch", "Cloud Infrastructure", "R&D", "Sales Ops"];

export { DEFAULT_CHART_OF_ACCOUNTS, PROJECTS };
